# This is a basic workflow to help you get started with Actions

name: WP DEPLOY

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [wordpress]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.ippus.us
#       upload only the compiled files
        local-dir: ./public/
        username: u711976272.IPPUSADMIN
        password: ${{ secrets.pw }}
